DROP DATABASE IF EXISTS ecommerce;
CREATE DATABASE ecommerce;
USE ecommerce;

CREATE TABLE SUPPLIER(
SUPP_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
SUPP_NAME VARCHAR(50) NOT NULL, 
SUPP_CITY VARCHAR(50) NOT NULL, 
SUPP_PHONE VARCHAR(50) NOT NULL
);
DESC SUPPLIER;

CREATE TABLE CUSTOMER(
CUS_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CUS_NAME VARCHAR(20) NOT NULL,
CUS_PHONE VARCHAR(10) NOT NULL,
CUS_CITY VARCHAR(30) NOT NULL,
CUS_GENDER ENUM('M', 'F') NOT NULL
);
DESC CUSTOMER;

CREATE TABLE CATEGORY(
CAT_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CAT_NAME VARCHAR(20) NOT NULL
);
DESC CATEGORY;

CREATE TABLE PRODUCT(
PRO_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
PRO_NAME VARCHAR(20) NOT NULL,
PRO_DESC VARCHAR(60),
CAT_ID INT UNSIGNED REFERENCES CATEGORY(CAT_ID)
);
DESC PRODUCT;

CREATE TABLE SUPPLIER_PRICING(
PRICING_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
PRO_ID INT UNSIGNED REFERENCES PRODUCT(PRO_ID),
SUPP_ID INT UNSIGNED REFERENCES SUPPLIER(SUP_ID),
SUPP_PRICE INT UNSIGNED DEFAULT 0
);
DESC SUPPLIER_PRICING;

CREATE TABLE ORDERS(
ORD_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ORD_AMOUNT INT UNSIGNED NOT NULL,
ORD_DATE DATE NOT NULL,
CUS_ID INT UNSIGNED REFERENCES CUSTOMER(CUS_ID),
PRICING_ID INT UNSIGNED REFERENCES SUPPLIER_PRICING(PRICING_ID)
);
DESC ORDERS;

CREATE TABLE RATING(
RAT_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ORD_ID INT UNSIGNED REFERENCES ORDERS(ORD_ID),
RAT_RATSTARS INT NOT NULL
);
DESC RATING;

INSERT INTO SUPPLIER(SUPP_NAME, SUPP_CITY, SUPP_PHONE) VALUES('Rajesh Retails','Delhi','1234567890'),
('Appario Ltd.','Mumbai','2589631470'),
('Knome products','Banglore','9785462315'),
('Bansal Retails','Kochi','8975463285'),
('Mittal Ltd.','Lucknow','7898456532');
SELECT * FROM SUPPLIER;

INSERT INTO CUSTOMER(CUS_NAME, CUS_PHONE, CUS_CITY, CUS_GENDER) VALUES('AAKASH','9999999999','DELHI','M'),
('AMAN','9785463215','NOIDA','M'),
('NEHA','9999999999','MUMBAI','F'),
('MEGHA','9994562399','KOLKATA','F'),
('PULKIT','7895999999','LUCKNOW','M');
SELECT * FROM CUSTOMER;

INSERT INTO CATEGORY(CAT_NAME) VALUES('BOOKS'),
('GAMES'),
('GROCERIES'),
('ELECTRONICS'),
('CLOTHES');
SELECT * FROM CATEGORY;

INSERT INTO PRODUCT(PRO_NAME, PRO_DESC, CAT_ID) VALUES('GTA V','Windows 7 and above with i5 processor and 8GB RAM',2),
('TSHIRT','SIZE-L with Black, Blue and White variations',5),
('ROG LAPTOP','Windows 10 with 15inch screen, i7 processor, 1TB SSD',4),
('OATS','Highly Nutritious from Nestle',3),
('HARRY POTTER','Best Collection of all time by J.K Rowling',1),
('MILK','1L Toned MIlk',3),
('Boat Earphones','1.5Meter long Dolby Atmos',4),
('Jeans','Stretchable Denim Jeans with various sizes and color',5),
('Project IGI','compatible with windows 7 and above',2),
('Hoodie','Black GUCCI for 13 yrs and above',5),
('Rich Dad Poor Dad','Written by RObert Kiyosaki',1),
('Train Your Brain','By Shireen Stephen',1);
SELECT * FROM PRODUCT;

INSERT INTO SUPPLIER_PRICING(PRO_ID, SUPP_ID, SUPP_PRICE) VALUES(1,2,1500),
(3,5,30000),
(5,1,3000),
(2,3,2500),
(4,1,1000),
(12,2,780),
(12,4,789),
(3,1,31000),
(1,5,1450),
(4,2,999),
(7,3,549),
(7,4,529),
(6,2,105),
(6,1,99),
(2,5,2999),
(5,2,2999);

SELECT * FROM SUPPLIER_PRICING;

ALTER TABLE ORDERS AUTO_INCREMENT = 101;
INSERT INTO ORDERS(ORD_AMOUNT, ORD_DATE, CUS_ID, PRICING_ID) VALUES(1500,'2021-10-06',2,1),
(1000,'2021-10-12',3,5),
(30000,'2021-09-16',5,2),
(1500,'2021-10-05',1,1),
(3000,'2021-08-16',4,3),
(1450,'2021-08-18',1,9),
(789,'2021-09-01',3,7),
(780,'2021-09-07',5,6),
(3000,'2021-09-10',5,3),
(2500,'2021-09-10',2,4),
(1000,'2021-09-15',4,5),
(789,'2021-09-16',4,7),
(31000,'2021-09-16',1,8),
(1000,'2021-09-16',3,5),
(3000,'2021-09-16',5,3),
(99,'2021-09-17',2,14);
SELECT * FROM ORDERS;

INSERT INTO RATING(ORD_ID,RAT_RATSTARS) VALUES(101,4),
(102,3),
(103,1),
(104,2),
(105,4),
(106,3),
(107,4),
(108,4),
(109,3),
(110,5),
(111,3),
(112,4),
(113,2),
(114,1),
(115,1),
(116,0);

SELECT * FROM RATING;

/*
3)Display the total number of customers based on gender who have placed orders of worth at least Rs.3000.
*/
SELECT CUS_GENDER AS CUSTOMER_GENDER, COUNT(DISTINCT C.CUS_ID) AS NO_OF_CUSTOMRES FROM CUSTOMER C INNER JOIN 
(SELECT CUS_ID FROM ORDERS WHERE ORD_AMOUNT >=3000) AS O ON C.CUS_ID = O.CUS_ID GROUP BY CUS_GENDER;

/*
 4)	Display all the orders along with product name ordered by a customer having Customer_Id=2
*/
SELECT O.*, T.PRO_NAME FROM ORDERS O INNER JOIN  
(SELECT PRICING_ID, PRO_NAME FROM SUPPLIER_PRICING SP INNER JOIN PRODUCT P ON SP.PRO_ID = P.PRO_ID)
AS T ON O.PRICING_ID = T.PRICING_ID WHERE CUS_ID = 2;

/*
5)Display the Supplier details who can supply more than one product.
*/
SELECT S.* FROM SUPPLIER S INNER JOIN  
(SELECT SUPP_ID, COUNT(PRO_ID) AS NO_OF_PRODUCTS FROM SUPPLIER_PRICING GROUP BY SUPP_ID) 
AS T ON S.SUPP_ID = T.SUPP_ID WHERE T.NO_OF_PRODUCTS >1 ORDER BY S.SUPP_ID;

/*
6)Find the least expensive product from each category and print the table with category id, name, product name and price of the product
*/
SELECT C.CAT_ID AS CATEGORY_ID, C.CAT_NAME AS CATEGORY_NAME , PRO_NAME AS PRODUCT_NAME, PRICE FROM CATEGORY C INNER JOIN 
(SELECT CAT_ID,MIN(SUPP_PRICE) AS PRICE FROM SUPPLIER_PRICING SP INNER JOIN PRODUCT P ON SP.PRO_ID = P.PRO_ID GROUP BY CAT_ID) AS T1 ON C.CAT_ID = T1.CAT_ID 
INNER JOIN
(SELECT CAT_ID, PRO_NAME, SP.* FROM PRODUCT P INNER JOIN 
(SELECT PRO_ID, MIN(SUPP_PRICE) AS MINPRICE FROM SUPPLIER_PRICING GROUP BY PRO_ID) AS SP ON P.PRO_ID = SP.PRO_ID) AS T2 ON T1.CAT_ID = T2.CAT_ID WHERE T1.PRICE = T2.MINPRICE ORDER BY C.CAT_ID;

/*
7)	Display the Id and Name of the Product ordered after “2021-10-05”.
*/
SELECT P.PRO_ID AS PRODUCT_ID, PRO_NAME AS PRODUCT_NAME FROM PRODUCT P INNER JOIN 
(SELECT PRO_ID FROM SUPPLIER_PRICING SP INNER JOIN ORDERS O ON SP.PRICING_ID = O.PRICING_ID WHERE ORD_DATE > '2021-10-05') 
AS T ON T.PRO_ID = P.PRO_ID GROUP BY PRODUCT_ID ORDER BY PRODUCT_ID;

/*
8)	Display customer name and gender whose names start or end with character 'A'.
*/
SELECT CUS_NAME AS NAME, CUS_GENDER AS GENDER FROM CUSTOMER WHERE CUS_NAME LIKE '%A' OR CUS_NAME LIKE 'A%';

/*
9)	Create a stored procedure to display supplier id, name, rating and Type_of_Service. For Type_of_Service, If rating =5, print “Excellent Service”,If rating >4 print “Good Service”, If rating >2 print “Average Service” else print “Poor Service”.
*/
DELIMITER //

CREATE PROCEDURE RATINGPROC()
BEGIN

SELECT T3.SUPP_ID, T3.SUPP_NAME, T3.RATING,
CASE
WHEN RATING = 5 THEN 'Excellent Service'
WHEN RATING >4 THEN 'Good Service'
WHEN RATING >2 THEN 'Average Service'
ELSE 'Poor Service'
END AS TYPE_OF_SERVICE FROM
 (SELECT S.SUPP_ID, SUPP_NAME, AVG(T2.RATING) AS RATING FROM SUPPLIER S INNER JOIN
(SELECT SP.SUPP_ID, SP.PRICING_ID, T.RATING FROM SUPPLIER_PRICING SP INNER JOIN
(SELECT PRICING_ID, AVG(RAT_RATSTARS) AS RATING FROM RATING R INNER JOIN ORDERS O ON R.ORD_ID = O.ORD_ID GROUP BY PRICING_ID) AS T ON T.PRICING_ID = SP.PRICING_ID) AS T2 ON T2.SUPP_ID = S.SUPP_ID GROUP BY SUPP_ID) AS T3 ORDER BY T3.SUPP_ID;

END//

DELIMITER ;

CALL RATINGPROC();